export const filterData = [
  {
    name: "status",
    label: "Status",
    filterTypes: ["None", "Alive", "Dead", "Unknown"],
  },
  {
    name: "species",
    label: "Species",
    filterTypes: [
      "None",
      "Human",
      "Alien",
      "Humanoid",
      "unknown",
      "Poopybutthole",
      "Mythological Creature",
      "Animal",
      "Robot",
      "Cronenberg",
      "Disease",
    ],
  },
  {
    name: "type",
    label: "Type",
    filterTypes: [
      "None",
      "Parasite",
      "Genetic experiment",
      "Human with antennae",
      "Robot-Crocodile hybrid",
      "Cromulon",
      "Animal",
      "Vampire",
      "Demon",
      "Giant",
      "Robot",
      "Cyborg",
    ],
  },
  {
    name: "gender",
    label: "Gender",
    filterTypes: ["None", "All", "Male", "Female", "Unknown", "Genderless"],
  },
];
